### ISSUE TITLE
ValueError: time data '2022-09-29T06:36:07+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

### ISSUE THREAD

**Issue by cwawak** [bentekkie/ha-generac#84]
Home Assistant version: 2013.12
Generac custom component version: 55a3c09420bf8
Python version: 3.11
Installation method: Docker
Description: A ValueError is raised when the datetime string obtained from the Generac integration does not match the expected format. This error appears to be caused by a mismatch between the expected datetime format with milliseconds (%Y-%m-%dT%H:%M:%S.%f%z) and the actual data string, which does not contain milliseconds ('2022-09-29T06:36:07+00:00').

Steps to Reproduce:

Ensure that the Generac custom component is installed and configured.
Operate Home Assistant until it performs an update check on the Generac entities.
Observe the error in the Home Assistant logs during the update interval of the Generac custom component.
Expected behavior: The datetime string from the Generac component should be processed without any error, and entities should be updated accordingly.
## Debug log

```
2023-12-31 07:44:02.657 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/generac/entity.py", line 83, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/generac/sensor.py", line 232, in native_value
    return datetime.strptime(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-09-29T06:36:07+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'
```

**Comment by bentekkie** [comment]
Fixed in https://github.com/bentekkie/ha-generac/pull/90
